SystemOrganization addCategory: #'ShoreLine-API'!
SystemOrganization addCategory: 'ShoreLine-API-Adapters'!
SystemOrganization addCategory: 'ShoreLine-API-Data'!
SystemOrganization addCategory: 'ShoreLine-API-Decoders'!
SystemOrganization addCategory: 'ShoreLine-API-Exceptions'!
SystemOrganization addCategory: 'ShoreLine-API-Presenters'!
SystemOrganization addCategory: 'ShoreLine-API-Routes'!
SystemOrganization addCategory: 'ShoreLine-API-Server'!
